from numpy import linspace as np__linspace, median as np__median, subtract as np__subtract
from pyqtgraph import BarGraphItem, mkPen

from .config import OSCRSettings
from .theme import AppTheme
from .widgets import AnalysisPlot, LegendPlot


class AnalysisGraphs():
    """Manages overview and analysis graphs."""

    def __init__(self, theme: AppTheme, settings: OSCRSettings):
        self._theme: AppTheme = theme
        self._settings: OSCRSettings = settings

        self.dps_bar_plot: LegendPlot
        self.dps_graph_plot: LegendPlot
        self.dmg_bar_plot: LegendPlot
        self.damage_out_plot: AnalysisPlot
        self.damage_in_plot: AnalysisPlot
        self.heal_out_plot: AnalysisPlot
        self.heal_in_plot: AnalysisPlot

    def create_overview_plots(self):
        """
        Creates and styles overview plots and returns them.
        """
        self.dps_bar_plot = LegendPlot(self._theme, y_font='app')
        self.dps_bar_plot.set_padding_fraction(0.01)
        self.dps_graph_plot = LegendPlot(self._theme, x_unit='s')
        self.dmg_bar_plot = LegendPlot(self._theme, x_unit='s')

    def plot_overview_data(
            self, overview_table: list[list], dps_graph_data: dict[str, tuple],
            dmg_bar_data: dict[str, tuple], time_data: dict[str, tuple]):
        """
        Plots overview data into DPS bar, DPS line graph and Damage bar plot widgets.

        Parameters:
        - :param overview_table: table with players and their total DPS values
        - :param dps_graph_data: DPS history data
        - :param dmg_bar_data: DMG history data
        - :param time_data: time reference to plot history data against
        """
        self.plot_horizontal_bar(overview_table, self.dps_bar_plot)
        self.dps_bar_plot.show_plot()
        self.plot_graph(dps_graph_data, time_data, self.dps_graph_plot)
        self.dps_graph_plot.show_plot()
        self.plot_grouped_bars(dmg_bar_data, time_data, self.dmg_bar_plot)
        self.dmg_bar_plot.show_plot()

    def plot_horizontal_bar(self, table: list[list], plot_widget: LegendPlot):
        """
        Creates bar plot from table and returns layout in which the graph was inserted.

        Parameters:
        - :param table: overview table as generated by the parser
        - :param plot_widget: plot widget that will be plotted to
        """
        table.sort(key=lambda line: line[2], reverse=True)
        y_annotations = (tuple((index + 1, line[0] + line[1]) for index, line in enumerate(table)),)
        plot_widget.set_axis_ticks('left', y_annotations)
        x = tuple(line[2] for line in table)
        y = tuple(range(1, len(x) + 1))
        plot_widget.set_x_range(0, max(x) * 1.05, padding=0)
        bars = BarGraphItem(
                x0=0, y=y, height=0.75, width=x, brush=self._theme['defaults']['mfg'], pen=None)
        plot_widget.clear()
        plot_widget.add_item(bars)

    def plot_graph(
            self, data: dict[str, tuple], time_reference: dict[str, tuple],
            plot_widget: LegendPlot):
        """
        Creates line plot from data and returns layout that countins the plot.

        Parameters:
        - :param data: dictionary containing the data to be plotted
        - :param time_reference: contains the time values for the data points
        - :param plot_widget: graph widget that will be plotted to

        :return: layout containing the graph
        """
        legend_data = list()
        plot_widget.clear()
        for (player, graph_data), color in zip(data.items(), self._theme['plot']['color_cycler']):
            if player in time_reference:
                time_data = time_reference[player]
                plot_widget.plot(time_data, graph_data, pen=mkPen(color, width=1.5))
                legend_data.append((color, player))
        plot_widget.create_legend(legend_data)

    def plot_grouped_bars(
            self, data: dict[str, tuple], time_reference: dict[str, tuple],
            plot_widget: LegendPlot):
        """
        Creates a bar plot with grouped bars.

        Parameters:
        - :param data: dictionary containing the data to be plotted
        - :param time_reference: contains the time values for the data points
        - :param plot_widget: bar widget that will be plotted to (supplied by decorator)

        :return: layout containing the graph (returned by decorator)
        """
        legend_data = list()
        group_width = self._settings.graph_resolution * 0.9
        player_num = len(data)
        if player_num == 0:
            return
        bar_width = group_width / player_num
        relative_bar_positions = np__linspace(
            0 + bar_width / 2, group_width - bar_width / 2, player_num)
        bar_position_offsets = relative_bar_positions - np__median(relative_bar_positions)

        plot_widget.clear()
        zipper = zip(data.items(), self._theme['plot']['color_cycler'], bar_position_offsets)
        for (player, graph_data), color, offset in zipper:
            if player in time_reference:
                time_data = np__subtract(time_reference[player], offset)
                bars = BarGraphItem(
                        x=time_data, width=bar_width, height=graph_data, brush=color, pen=None,
                        name=player)
                plot_widget.add_item(bars)
                legend_data.append((color, player))
        plot_widget.create_legend(legend_data)
