name: oscr_ui_deb_build

services:
  oscr_ui_deb_build:
    image: oscruideb
    build:
      context: .
      dockerfile: build_deb.Dockerfile
    container_name: running_oscr_ui_deb_build
    volumes:
      - type: bind
        source: ../
        target: /mnt/
        read_only: false
    command:
      - /bin/sh
      - -c
      - |
        cd /mnt
        distribution/build_pyinstaller.sh
        distribution/package_deb.sh
    