name: Build Windows Installer via Inno Compiler

on:
  workflow_dispatch:

jobs:
  build_windows_binary:
    name: Build Windows Binary (PyInstaller + Inno)
    runs-on: {{ $matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Attempting something new by caching pip dependencies because it's
      # taking forever to get to the inno install.
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pyinstaller==6.10.0" `
                                "PySide6==6.10.0" `
                                "pyqtgraph==0.13.7" `
                                "numpy==2.2.4" `
                                "STO-OSCR==2025.8.10.0" `
                                "OSCR-django-client==2025.7.19.0" `
                                "pydantic==2.12.3"

      - name: Build OSCR-UI Executable with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --name OSCR-UI --onedir main.py `
            --add-data "assets;assets" --add-data "locales;locales" `
            --windowed --icon "assets\oscr_icon_small.ico"


      - name: Compile Inno Setup Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: OSCR-UI.iss
          options: /Odist /Qp # Output to dist/ and /Qp should show errors.

      - name: Upload PyInstaller Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSCR-UI_PyInst_ZipFile
          path: dist/OSCR-UI.zip

      - name: Upload Inno Setup Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSCR-UI_Installer_Exe
          path: dist/*.exe # Robust: catches any .exe in dist/
