name: Build Wheel and Publish to PyPI

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: python3 -m pip install build
      - run: python3 -m build  # creates dist/*
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
