name: Build Linux Binary (PyInstaller)

on:
  workflow_dispatch:

jobs:
  build_pyinst_linux:
    name: Build Linux Binary (PyInstaller)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install Python Dependencies
      - run: python -m pip install pyinstaller==6.10.0 PySide6==6.10.0 pyqtgraph==0.13.7 numpy==2.3.4 STO-OSCR>=2025.8.10.0 OSCR-django-client>=2025.7.19.0 pydantic>=2.12.3

      - name: Build OSCR-UI Binary PyInstaller
      - run: pyinstaller --name OSCR-UI --onedir main.py --add-data=assets:assets --add-data=locales:locales

      - name: Compress PyInstaller Output
        run: |
          cd dist
          tar -czf OSCR-UI.tgz OSCR-UI

      - uses: actions/upload-artifact@v4
        with:
          name: OSCR-UI_PyInst_TarBall
          path: dist/OSCR-UI.tgz
